services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournaments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tournaments"]
      interval: 5s
      timeout: 5s
      retries: 10
   

  migrations:
    build: .
    command: bash -c "sleep 10 && alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/tournaments

  web:
    build: .
    command: bash -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migrations
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/tournaments

volumes:
  postgres_data: